name: TEST

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v4

      - name: 스크립트 실행
        run: echo "스케줄러가 성공적으로 실행되었습니다!"
