name: MVNO Monitor

on:
  schedule:
    - cron: '0 1 * * *' # 미국1시 한국10시
    #- cron: '*/15 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install packages
        run: pip install -r requirements.txt

      #- name: Check MVNOHub
      #  run: python check_mvno.py
      
      - name: Check MOYO
        run: python check_moyo.py  

      - name: Commit state file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: update mvno state
